version: '2'
services:
  web:
    image: friism/pg-test-web
    build:
      context: .
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
